### ISSUE TITLE
 _dataSource.numberOfItems(in: section) always return zero

### ISSUE THREAD

**Issue by steve21124** [muukii/DataSources#3]
Great library. thanks for sharing. 
Not sure where I did the mistake. it always return zero when calling  _dataSource.numberOfItems(in: section) . Basically, I am trying to see if DataSources will work without using RxSwift and RxCocoa. Since the demo only use (RxSwift and RxCocoa)

`
    private lazy var _dataSource: DataSource<CollectionViewAdapter> = .init(adapter: .init(collectionView: self.collectionView))
    
    private let section0 = Section(ModelA.self, isEqual: { $0.identity == $1.identity })
    
    var section0Models: [ModelA] = [ModelA(identity: UUID().uuidString, title: String.randomEmoji())] {
        didSet {
            _dataSource.update(
                in: section0,
                items: section0Models,
                updateMode: .partial(animated: true),
                completion: {
                    
            })
        }
    }

        for _ in 0..<20 {
            _dataSource.add(section: section0)
        }
        for _ in 0..<20 {           
            section0Models.append(ModelA(identity: UUID().uuidString, title: String.randomEmoji()))
        }

   // then calling this below always return zero. do you know why?
_dataSource.numberOfItems(in: 0)

`

**Comment by muukii** [comment]
@steve21124 
Thank you.
I think you should not add section 20 times.

**Comment by muukii** [comment]
@steve21124 
I've added validation.
https://github.com/muukii/DataSources/commit/94aba9b5bd09a1da9361c1a3409a1fe917edd1f9

Thank you!

**Comment by muukii** [comment]
@steve21124 
And also, I've renamed few classes.
Please, check this PR.
https://github.com/muukii/DataSources/pull/2

**Comment by steve21124** [comment]
Thank you for the help. 
https://gist.github.com/steve21124/cf1a11e30b58e6957812fdbea583de01

I still have problem with this line 
https://gist.github.com/steve21124/cf1a11e30b58e6957812fdbea583de01#file-viewcontroller-L48

It return zero items. Do you have simple example without using "RxSwift and RxCocoa" ?

**Comment by muukii** [comment]
@steve21124 
Hi, Thank you for sample code.

I've fixed your code. please check it.
https://gist.github.com/muukii/dac32876237c127cbfa4fc0257905686

And sorry.
Calling `update` will be throttled, therefore updating `numberOfItems` will be updated asynchronously.

You can get an actual count of data in update.completion closure.

**Comment by steve21124** [comment]
Thank you so much for the fixes. Now it make sense. It take a while to debug it. :) 

With this sample code, I now know, it will work without using "RxSwift and RxCocoa" .

**Comment by steve21124** [comment]
fyi: currently, i am planning to remove  "import RxSwift, EasyPeasy, AsyncDisplayKit"  dependencies of Component.swift the reason because I am using ios 11 beta 5 and these libraries is not compatible yet with swift 4.0. If you do have solution for it. feel free to share it. Thank you
