### ISSUE TITLE
Can't install via Cocoapods

### ISSUE THREAD

**Issue by Xopoko** [muukii/DataSources#4]
Mac-mini-admin-2:TestProject admin$ pod install
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040777
Analyzing dependencies
**[!] Unable to find a specification for `DataSources`**

**Comment by muukii** [comment]
@Xopoko 
Hmm, 
I want you to try `pod repo update`.
Then, try `pod install` again.

**Comment by Xopoko** [comment]
@muukii 
Aww, thank! That work for me.
